### ISSUE TITLE
Cannot convert extension 'wsdl2java' to a task.

### ISSUE THREAD

**Issue by mhlmhlmhlmhl** [bjornvester/wsdl2java-gradle-plugin#12]
I want to make the compileJava Gradle task dependent upon (happen after) the wsdl2java task, so I added this to my Gradle build file:

```
wsdl2java {
}
compileJava {
    dependsOn wsdl2java
}
```

... but I get

```
`Could not determine the dependencies of task ':compileJava'.
> Cannot convert extension 'wsdl2java' to a task.
  The following types/formats are supported:
    - A String or CharSequence task name or path
    - A Task instance
    - A TaskReference instance
    - A Buildable instance
    - A TaskDependency instance
    - A Provider that represents a task output
    - A Provider instance that returns any of these types
    - A Closure instance that returns any of these types
    - A Callable instance that returns any of these types
    - An Iterable, Collection, Map or array instance that contains any of these types
 ```

I am using "com.github.bjornvester.wsdl2java" version "1.1"  with Gradle 6.9 and Java 11.

**Comment by zohanalexix** [comment]
I have the same issue on wsdl2java version 1.2, gradle 7.2, java 11.

As a workaround, I used something like this, which works:
`
task myCustomTask (type: GradleBuild) {
	tasks = ['wsdl2java', 'compileJava']
}
`

**Comment by bjornvester** [comment]
The `wsdl2java` task is already configured to run before compiling the source code. There should be no need for manually setting up task dependencies. Let me know if you have an example where it is not run before compiling.
