### ISSUE TITLE
Support for Java 17 

### ISSUE THREAD

**Issue by sushilkumart** [bjornvester/wsdl2java-gradle-plugin#22]
Current plugin version does not support Java 17

**Comment by tretail** [comment]
Could you elaborate? Maybe with a mcve?

I use this plugin on my side, with java17 toolchain. Bytecode is generated with version 61 (which match java 17).

**Comment by bjornvester** [comment]
Yes, it already supports Java 17. When using CXF 4 and the jakarta namespace (instead of javax), it is actually the _minimum_ required version.
