### ISSUE TITLE
Issue with gradle version 7.0

### ISSUE THREAD

**Issue by TomBAMU** [bjornvester/wsdl2java-gradle-plugin#5]
Hi bjorn,

upgrading to gradle version 7.0 causes an error in combination with the plugin.

> Type 'Wsdl2JavaTask' property 'sourcesOutputDir' is annotated with @PathSensitive but that is not allowed for 'OutputDirectory' properties.
     Reason: This modifier is used in conjunction with a property of type 'OutputDirectory' but this doesn't have semantics.
    Possible solution: Remove the '@PathSensitive' annotation.
   Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#incompatible_annotations for more details about this problem.

Is it possible to remove this issue in a newer version of this plugin?

I could open a PR with the possible solution, but I'm not sure this issue will resolve all incompatibilities with gradle 7.0. Looking forward to your response

Thanks

**Comment by bjornvester** [comment]
Thank you for the report, and apologies for the very late response. It has been fixed in the newest version of the plugin.
